### ISSUE TITLE
キックオフ

### ISSUE THREAD

**Issue by ninomae** [imobile/DDDReadingCircle#1]
1. 輪読の進め方（新しい案でも、既存の案のブラッシュアップでも可）
2. 輪読の周期
3. 担当者の責務（輪読の進め方に入るかも）
4. 輪読を完走するためにあったら良いと思うルール
5. 初回開催日と担当者と範囲決定

**Comment by im-higashi** [comment]
@ninomae :+1:

**Comment by im-higashi** [comment]
## 輪読の進め方
- 論点は担当、メンバーそれぞれがgithub issueとして事前に提示する
  - 事前にある程度議論しても寄りがcloseは基本発表の時に行うこと
- 担当は事前に対象のisuueへのリンクを含んだテキストをmdファイルとしてUpする

## 輪読の周期

 2週間に1度で20ページ目安

## 担当者の責務
- 発表資料をmdファイルとしてUpする(issueへのリンクでも良い）

## 輪読を完走するためにあったら良いと思うルール
- 1部終わる毎に振り返り会を設ける  
- その他はやりながら見つける

## 初回開催日と担当者と範囲決定
- 厳正な抽選で @ninomae さんに
- 1章と2章（読めれば）
- 4 月 26 日 （火） 17 時 15 分 ～ 18 時 15 分 WHITE

**Comment by im-higashi** [comment]
@ninomae 問題なければCloseしてください
