### ISSUE TITLE
2章 ユビキタス言語とは

### ISSUE THREAD

**Issue by ninomae** [imobile/DDDReadingCircle#4]
以下のどれがユビキタス言語であるか？
- アドネットワーク
- スポット
- XID

ユビキタス言語は、ドメインエキスパートと開発者がいて初めて成り立つものなのか？

**Comment by im-higashi** [comment]
ユビキタス言語の要件が
ドメインエキスパートとの共通語という意味であれば、どれもがユビキタス言語と言えると思います。
ただ、モデルとして同じ言葉が使えているかというと疑問が残りますね。

特にXIDは配信側にモデルを作らなかったことは悔やんでいる点です。
※XIDは現在はプリミティブな値型

もう少し２章を読み進めれば意見が変わるかも・・

**Comment by SatoshiKawamoto** [comment]
スポットだけがユビキタスかな・・・？
