### ISSUE TITLE
モデル駆動設計の実現に適したプログラミング言語

### ISSUE THREAD

**Issue by 7pairs** [imobile/DDDReadingCircle#7]
モデル駆動設計の実現に適したプログラミング言語（パラダイム）の条件とは何か？

本文中では、オブジェクト指向の利点は下記のように述べられている。

> オブジェクト指向プログラミングが強力なのは、あるモデリングパラダイムに基づいていて、モデルを構成する概念に実装を提供するからだ。プログラマから見る限り、オブジェクトは実際にメモリ上に存在していて、他のオブジェクトと関連を持ち、クラスとして構成されている。また、メッセージングによって呼び出せるふるまいも提供する。

一方で、Prologのような述語論理パラダイムの言語もモデル駆動設計と適合すると書かれている。また、数学のモデル（の一部）はFORTRANで表現できるとも書かれている。

どんな条件を満たせば、モデル駆動設計を実現できる言語と言えるのか？

**Comment by im-higashi** [comment]
モデルを記述出来るだけでなく、ソフトウェア設計の原則を満たせることが要件でないかと思います。
ここで原則と言っているものはSOLIDをベースとしたものを指します
- SOLID原則
  - 単一責任の原則（S）
  - オープン・クローズドの原則（O）
  - リスコフの置換原則（L）
  - 依存関係逆転の原則（D）
  - インターフェイス分離の原則（I）

現代的言語で上記を満たせないものはほぼ無いと考えています。
例えば、javascriptなどはinterfaceが存在しませんが
イディオムを利用すれば対応は可能、またTypeScriptなどをAltJSを使うのも手かと

モデルを記述する上では
クラス・インターフェイス指向言語が静的解析性が高いので利点は大きいと考えますが
その他でも実務上の問題はないのかと

個人的にはクラス・インターフェイス指向言語が
モデルに対してコンパイルタイムでの制約がかけられるので好みではあります :smile:
